forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-nodejs'

mod 'puppetlabs-stdlib',
  :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"

mod 'puppetlabs-apache'

mod 'puppetlabs-apt'
